### PR TITLE
Deprecate @register_job decorator.

### PR DESCRIPTION
**Pull request by jcass77**
See: https://github.com/jarekwg/django-apscheduler/pull/119

### CODE REVIEW

**Comment by redstoneleo** [comment]
@jcass77
1. It is necessary to add description as I have written [here](https://github.com/jarekwg/django-apscheduler/pull/119/commits/293568ab2f5dd4ef38f202701c1667209417b4b4) to help ease the effort of apscheduler newbies like me.  
2. For the same reason, I also suggest that adding the minimum necessary  instructions on using supervisor in collaboration with django-apscheduler.

**Comment by redstoneleo** [comment]
@jcass77 Any consideration on my suggestion ?

**Comment by jcass77** [comment]
> - One can also use APScheduler's decorator version of [`add_job()`](https://apscheduler.readthedocs.io/en/latest/modules/schedulers/base.html#apscheduler.schedulers.base.BaseScheduler.add_job"apscheduler.schedulers.base.BaseScheduler.add_job") - [`@scheduler.scheduled_job`](https://apscheduler.readthedocs.io/en/latest/modules/schedulers/base.html#apscheduler.schedulers.base.BaseScheduler.scheduled_job) to register a job,e.g. 

The README is just intended to provide a short, concise, example and we include links to the official APScheduler documentation for further details on all of the different ways in which APScheduler can be used.

Is there a specific use case where using the decorated versions of the APScheduler methods are preferable that you think we may be missing?

> For the same reason, I also suggest that adding the minimum necessary instructions on using supervisor in collaboration with django-apscheduler.

When it comes to recommendations on how to incorporate django-apscheduler into an existing project's deployment workflow there are only two scenarios that I can think of:

1. Users are already using supervisor to start and monitor their Django apps in production, in which case this should be a trivial addition for them (i.e. they will already have a working example used to start their web server).

2. Users are using something else, in which case they can ignore the reference to supervisor and use whatever they are comfortable with.

Adding our own attempt at best practice guidelines for deploying Django apps in production using supervisor won't be helpful for the users in (1) above as they will already have a tried and tested approach that they should prefer using, and will be irrelevant for the users in (2) as they are already using something else?

**Comment by redstoneleo** [comment]
What if adding the instruction  I have written in a quick-start guide rather than README? I still think it is helpful for those who are new to APScheduler , supervisor and  django-apscheduler.

> Is there a specific use case where using the decorated versions of the
> APScheduler methods are preferable that you think we may be missing?

I prefer [`@scheduler.scheduled_job`](https://apscheduler.readthedocs.io/en/latest/modules/schedulers/base.html#apscheduler.schedulers.base.BaseScheduler.scheduled_job) to [`add_job()`](https://apscheduler.readthedocs.io/en/latest/modules/schedulers/base.html#apscheduler.schedulers.base.BaseScheduler.add_job%22apscheduler.schedulers.base.BaseScheduler.add_job%22) for the decorated version is more tight - the job registration operation  is just above the implementation of the job function, I think it would make  code maintenance easy in future even though every modern IDE comes with a 'jump to definition' feature.

**Pull request merged**
